//! Round trips against genuine Word-authored files.
//!
//! ## Why these tests are gated on an environment variable
//!
//! Everything in this repository's test suite so far has run against fixtures
//! generated by our own code. That is fine for *behaviour* and useless for
//! *fidelity*: a fixture built from the same assumptions as the implementation
//! confirms those assumptions.
//!
//! The proof that arrived: `tests/document_bytes.rs` passes, and yet the
//! generated fixtures missed a real bug that made **every XML part of a genuine
//! Word file** fail to round trip byte-identically. The fixtures had no trailing
//! newline; every real OOXML part has one.
//!
//! So these tests point at real files via `U1_DOCS_REAL_DOCX`, a
//! semicolon-separated list of paths. They skip — visibly, with a reason — when
//! the variable is unset. That keeps CI deterministic while making it possible
//! to run the real thing locally, and on any machine that has documents to hand.
//!
//! ## Running them
//!
//! ```text
//! set U1_DOCS_REAL_DOCX=C:\path\to\a.docx;C:\path\to\b.docx
//! cargo test --test real_documents -- --nocapture
//! ```
//!
//! On PowerShell:
//!
//! ```powershell
//! $env:U1_DOCS_REAL_DOCX = "C:\docs\a.docx;C:\docs\b.docx"
//! cargo test --test real_documents -- --nocapture
//! ```
//!
//! ## What a failure here means
//!
//! A failure is a bug in U1 Docs, full stop. The file is valid; Word wrote it.
//! We are not entitled to "improve" it.

use std::path::{Path, PathBuf};

use u1_docs::ooxml::opc::Package;
use u1_docs::ooxml::tree::{Document, Node};

/// Environment variable holding semicolon-separated paths to real documents.
const ENV: &str = "U1_DOCS_REAL_DOCX";

fn real_documents() -> Vec<PathBuf> {
    std::env::var(ENV)
        .unwrap_or_default()
        .split(';')
        .map(str::trim)
        .filter(|s| !s.is_empty())
        .map(PathBuf::from)
        .collect()
}

/// A scratch path no two concurrently-running tests can collide on.
///
/// The obvious spellings are all wrong here. Cargo runs the tests in this file
/// in parallel threads, so a name derived only from the source file is shared
/// across tests. And `{:?}` on a path renders the quotes and backslashes of the
/// Windows form into the filename, which `CreateFile` rejects outright — so a
/// debug-formatted path is not a path.
fn scratch_path(source: &std::path::Path) -> PathBuf {
    use std::sync::atomic::{AtomicU32, Ordering};
    static SEQ: AtomicU32 = AtomicU32::new(0);

    let stem = source
        .file_stem()
        .map(|s| s.to_string_lossy().into_owned())
        .unwrap_or_else(|| "doc".to_string());
    // Keep only characters that are legal everywhere; the stem is only for
    // readability when a test fails and prints the path.
    let stem: String = stem
        .chars()
        .filter(|c| c.is_ascii_alphanumeric() || *c == '-' || *c == '_')
        .collect();
    let stem = if stem.is_empty() { "doc" } else { &stem };

    std::env::temp_dir().join(format!(
        "u1-docs-real-{}-{}-{}.docx",
        std::process::id(),
        SEQ.fetch_add(1, Ordering::Relaxed),
        stem
    ))
}

/// What we learned from each file, whether it passed or not.
struct Report {
    parts: usize,
    xml_parts: usize,
    parse_failures: Vec<(String, String)>,
    byte_mismatches: Vec<String>,
    round_trip_failures: Vec<String>,
}

/// Exercise the full open → save → open path on one real file.
fn check(path: &Path) -> Report {
    let mut report = Report {
        parts: 0,
        xml_parts: 0,
        parse_failures: Vec::new(),
        byte_mismatches: Vec::new(),
        round_trip_failures: Vec::new(),
    };

    let pkg = match Package::open(path) {
        Ok(p) => p,
        Err(e) => {
            report
                .parse_failures
                .push(("<package>".into(), e.to_string()));
            return report;
        }
    };
    report.parts = pkg.parts().len();

    // Every XML part must parse, and parse to the same bytes.
    for part in pkg.parts() {
        if !(part.name().ends_with(".xml") || part.name().ends_with(".rels")) {
            continue;
        }
        report.xml_parts += 1;
        match Document::parse(part.bytes()) {
            Ok(doc) => {
                if doc.serialize() != part.bytes() {
                    report.byte_mismatches.push(part.name().to_string());
                }
            }
            Err(e) => report
                .parse_failures
                .push((part.name().to_string(), e.to_string())),
        }
    }

    // Full package round trip.
    let tmp = scratch_path(path);
    match pkg.save(&tmp) {
        Ok(()) => match Package::open(&tmp) {
            Ok(after) => {
                if after.parts().len() != pkg.parts().len() {
                    report.round_trip_failures.push(format!(
                        "part count {} -> {}",
                        pkg.parts().len(),
                        after.parts().len()
                    ));
                } else {
                    for (a, b) in pkg.parts().iter().zip(after.parts()) {
                        if a.name() != b.name() || a.bytes() != b.bytes() {
                            report
                                .round_trip_failures
                                .push(format!("{} changed", a.name()));
                        }
                    }
                }
            }
            Err(e) => report.round_trip_failures.push(format!("reopen: {e}")),
        },
        Err(e) => report.round_trip_failures.push(format!("save: {e}")),
    }
    let _ = std::fs::remove_file(&tmp);

    report
}

fn describe(path: &Path, report: &Report) {
    println!("\n{}", path.display());
    println!("  parts          {}", report.parts);
    println!("  xml parts      {}", report.xml_parts);
    println!("  parse failures {}", report.parse_failures.len());
    for (name, err) in &report.parse_failures {
        println!("      {name}: {err}");
    }
    println!("  byte mismatch  {}", report.byte_mismatches.len());
    for name in &report.byte_mismatches {
        println!("      {name}");
    }
    println!("  round trip     {}", report.round_trip_failures.len());
    for f in &report.round_trip_failures {
        println!("      {f}");
    }
}

/// Round trip every real document, reporting what happened.
#[test]
fn real_documents_round_trip_without_damage() {
    let docs = real_documents();
    if docs.is_empty() {
        println!(
            "skipping: set {ENV} to a semicolon-separated list of .docx paths \
             to run this against genuine Word output"
        );
        return;
    }

    let mut failures: Vec<String> = Vec::new();

    for path in &docs {
        assert!(
            path.exists(),
            "{ENV} names a file that does not exist: {}",
            path.display()
        );

        let report = check(path);
        describe(path, &report);

        if let Some((name, err)) = report.parse_failures.first() {
            failures.push(format!("{}: {name} did not parse: {err}", path.display()));
        }
        for name in &report.byte_mismatches {
            failures.push(format!(
                "{}: {name} did not round trip byte-identically",
                path.display()
            ));
        }
        for f in &report.round_trip_failures {
            failures.push(format!("{}: {f}", path.display()));
        }
    }

    assert!(
        failures.is_empty(),
        "{} failure(s) across {} real document(s):\n  {}",
        failures.len(),
        docs.len(),
        failures.join("\n  ")
    );
}

/// A separate test so a parse failure and a fidelity failure are distinguishable
/// in CI output.
#[test]
fn real_documents_parse_completely() {
    let docs = real_documents();
    if docs.is_empty() {
        println!("skipping: set {ENV} to run this");
        return;
    }

    let mut unparsed: Vec<String> = Vec::new();
    for path in &docs {
        let pkg = Package::open(path).unwrap_or_else(|e| panic!("{}: {e}", path.display()));
        for part in pkg.parts() {
            let is_xml = part.name().ends_with(".xml") || part.name().ends_with(".rels");
            if is_xml && let Err(e) = Document::parse(part.bytes()) {
                unparsed.push(format!("{}: {}: {e}", path.display(), part.name()));
            }
        }
    }

    assert!(
        unparsed.is_empty(),
        "parts that failed to parse:\n  {}",
        unparsed.join("\n  ")
    );
}

/// Extract every paragraph of every real document and check it behaves.
///
/// This is a different question from the round trip. A file can round trip
/// perfectly while the reader still gets the text wrong — and text extraction is
/// where "opens fine, reads wrong" lives.
///
/// The checks that can be asserted without knowing the document's contents:
///
/// - Every part parses.
/// - Every `w:body`'s children classify sensibly.
/// - Text extraction terminates and never panics, on parts with arbitrary
///   structure. This is the real check: an unfamiliar element anywhere in a real
///   document must not be able to crash the reader.
///
/// A file with no paragraphs is not a failure — python-docx's template, for one,
/// is genuinely empty.
#[test]
fn real_documents_expose_their_paragraphs() {
    use u1_docs::ooxml::wml::{Paragraph, TextOptions};

    let docs = real_documents();
    if docs.is_empty() {
        println!("skipping: set {ENV} to run this");
        return;
    }

    let mut total_paragraphs = 0usize;
    let mut bodies_seen = 0usize;

    for path in &docs {
        let pkg = Package::open(path).unwrap_or_else(|e| panic!("{}: {e}", path.display()));

        for part in pkg.parts() {
            if part.name() != "word/document.xml" {
                continue;
            }
            let doc = Document::parse(part.bytes())
                .unwrap_or_else(|e| panic!("{}: {part:?}: {e}", path.display()));
            let root = doc.root().expect("root");

            for body in root
                .descendant_elements()
                .filter(|n| n.local_name() == Some("body"))
            {
                bodies_seen += 1;
                for node in body.descendant_elements() {
                    if node.local_name() != Some("p") {
                        continue;
                    }
                    let paragraph = Paragraph::from_element(node)
                        .unwrap_or_else(|e| panic!("{}: {e}", path.display()));
                    // Both option sets must terminate and produce text.
                    let _ = paragraph.text(TextOptions::default());
                    let _ = paragraph.text(TextOptions {
                        include_deletions: true,
                        normalise_whitespace: false,
                    });
                    let _ = paragraph.runs().count();
                    let _ = paragraph.symbols().count();
                    total_paragraphs += 1;
                }
            }
        }

        println!("{}: {total_paragraphs} paragraph(s) so far", path.display());
    }

    println!("bodies: {bodies_seen}, paragraphs: {total_paragraphs}");
    assert!(
        bodies_seen > 0,
        "no w:body found in any real document; the traversal is not finding the body"
    );
}

/// No character in a `w:t` may go missing.
///
/// This is the check that would have caught every bug the semantics layer is
/// prone to. Runs nest, fields hide instruction text, deletions hide deleted
/// text, and namespaces hide whole subtrees — each of those is a way for
/// `w:t` content to be silently dropped while the document still "works".
///
/// The assertion is derived from the file rather than hardcoded, so it holds for
/// any document: every non-whitespace character that appears in a paragraph's
/// `w:t` elements must appear in that paragraph's extracted text.
///
/// Deleted and field-instruction text is excluded deliberately — it is *supposed*
/// to be missing, and excluding it by name is the assertion that it is.
#[test]
fn real_documents_do_not_drop_text() {
    use u1_docs::ooxml::wml::{Paragraph, TextOptions};

    let docs = real_documents();
    if docs.is_empty() {
        println!("skipping: set {ENV} to run this");
        return;
    }

    let opts = TextOptions::default();
    let mut checked = 0usize;
    let mut missing_total = 0usize;

    for path in &docs {
        let pkg = Package::open(path).unwrap_or_else(|e| panic!("{}: {e}", path.display()));
        for part in pkg.parts() {
            if part.name() != "word/document.xml" {
                continue;
            }
            let doc = Document::parse(part.bytes()).expect("parse");
            let root = doc.root().expect("root");

            for node in root
                .descendant_elements()
                .filter(|n| n.local_name() == Some("p"))
            {
                let paragraph = match Paragraph::from_element(node) {
                    Ok(p) => p,
                    Err(_) => continue,
                };
                let extracted = paragraph.text(opts);

                let expected = expected_characters(node);
                let missing: Vec<char> = expected
                    .into_iter()
                    .filter(|c| !extracted.contains(*c))
                    .collect();

                if !missing.is_empty() {
                    missing_total += missing.len();
                    println!(
                        "{}: paragraph dropped {:?} (extracted {:?})",
                        path.display(),
                        missing,
                        extracted
                    );
                }
                checked += 1;
            }
        }
    }

    println!("checked {checked} paragraphs in real documents");
    assert_eq!(
        missing_total, 0,
        "{missing_total} character(s) present in a w:t were absent from the extracted text"
    );
}

/// The characters a paragraph's content elements are expected to contribute.
///
/// Walks the paragraph the naive way — every `w:t` in document order — and
/// collects the non-whitespace characters. Skips `w:delText` and `w:instrText`
/// because those are meant to be excluded, and subtrees that legitimately hold
/// foreign character data.
fn expected_characters(paragraph: &Node) -> Vec<char> {
    let mut out = Vec::new();
    let mut stack: Vec<&Node> = paragraph.descendant_elements().collect();
    stack.reverse();

    while let Some(node) = stack.pop() {
        let Some(local) = node.local_name() else {
            continue;
        };
        match local {
            // Expected to be absent.
            "delText" | "instrText" | "delInstrText" | "sym" => continue,
            // Foreign or duplicated content.
            "AlternateContent" | "Fallback" | "drawing" | "pict" | "object" => continue,
            _ => {}
        }

        if local == "t" {
            let raw = node.text_content();
            out.extend(raw.chars().filter(|c| !c.is_whitespace()));
            continue;
        }

        // Re-push this node's element children, reversed, to keep document order.
        let mut children: Vec<&Node> = node.children_elements().collect();
        children.reverse();
        for child in children {
            stack.push(child);
        }
    }

    out
}

/// A paragraph's text must be reproducible: parsing the same part twice gives the
/// same result. Anything else means the reader has hidden state or iteration
/// order we do not control.
#[test]
fn real_documents_extract_deterministically() {
    use u1_docs::ooxml::wml::{Paragraph, TextOptions};

    let docs = real_documents();
    if docs.is_empty() {
        println!("skipping: set {ENV} to run this");
        return;
    }

    for path in &docs {
        let pkg = Package::open(path).unwrap_or_else(|e| panic!("{}: {e}", path.display()));
        for part in pkg.parts() {
            if part.name() != "word/document.xml" {
                continue;
            }
            let doc = Document::parse(part.bytes()).expect("parse");
            let root = doc.root().expect("root");

            let once: Vec<String> = root
                .descendant_elements()
                .filter(|n| n.local_name() == Some("p"))
                .filter_map(|n| Paragraph::from_element(n).ok())
                .map(|p| p.text(TextOptions::default()))
                .collect();
            let twice: Vec<String> = root
                .descendant_elements()
                .filter(|n| n.local_name() == Some("p"))
                .filter_map(|n| Paragraph::from_element(n).ok())
                .map(|p| p.text(TextOptions::default()))
                .collect();

            assert_eq!(
                once,
                twice,
                "{}: extraction is not deterministic",
                path.display()
            );
        }
    }
}

/// Round trip every real document and report, without failing.
///
/// For a survey rather than a gate: run this when evaluating how U1 Docs does
/// against a folder of documents, before deciding what to fix.
#[test]
fn real_documents_survey() {
    let docs = real_documents();
    if docs.is_empty() {
        println!("skipping: set {ENV} to run this");
        return;
    }

    let mut clean = 0usize;
    let mut dirty = 0usize;

    for path in &docs {
        let report = check(path);
        describe(path, &report);
        let ok = report.parse_failures.is_empty()
            && report.byte_mismatches.is_empty()
            && report.round_trip_failures.is_empty();
        if ok {
            clean += 1;
        } else {
            dirty += 1;
        }
    }

    println!(
        "\n{clean} clean, {dirty} with problems, {} total",
        docs.len()
    );
}
